import {
  Document,
  Page,
  Text,
  View,
  Link,
  StyleSheet,
  Svg,
  Rect,
  Polyline,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { ReportData, Insight } from "@/lib/report/data";

/**
 * The portfolio report.
 *
 * Printed on paper, not screen. The app is brass-on-ink, but a dark PDF is a
 * document nobody can print and a wall of toner if they try — so this uses the
 * design system's `paper` ground with ink text and brass kept for accents. It is
 * recognisably the same product without being hostile to a printer.
 *
 * Built-in Helvetica throughout, deliberately: registering a web font means a
 * network fetch at render time inside a serverless function, which is a new way
 * for the download to fail for no visual gain in a financial table.
 *
 * Interactivity is what a PDF can actually honour — a bookmark outline every
 * reader shows in its sidebar, and links back into the app — rather than
 * pretending a page can hold a live chart.
 *
 * No `server-only` guard, unlike lib/report/data.ts: this module is pure
 * presentation over data handed to it, holds no session and reaches nothing. It
 * is left importable so the layout can be rendered against sample data — see
 * scripts/verify-report.ts — which is the only way to see a page break land
 * badly before a user does.
 */

const C = {
  paper: "#FBF9F5",
  panel: "#F2EEE6",
  ink: "#14161A",
  body: "#3D424D",
  muted: "#6B7280",
  rule: "#DED8CC",
  brass: "#9A7B1C",
  brassLight: "#C9A227",
  gain: "#2F7D4F",
  loss: "#C0392B",
  watch: "#B7791F",
};

const s = StyleSheet.create({
  page: {
    backgroundColor: C.paper,
    color: C.ink,
    paddingTop: 46,
    paddingBottom: 54,
    paddingHorizontal: 44,
    fontFamily: "Helvetica",
    fontSize: 9.5,
    lineHeight: 1.5,
  },
  eyebrow: { fontSize: 7.5, letterSpacing: 1.4, color: C.brass, fontFamily: "Helvetica-Bold" },
  h1: { fontSize: 25, fontFamily: "Helvetica-Bold", letterSpacing: -0.6, marginTop: 8 },
  h2: { fontSize: 13, fontFamily: "Helvetica-Bold", letterSpacing: -0.2, marginBottom: 10 },
  h3: { fontSize: 10, fontFamily: "Helvetica-Bold" },
  muted: { color: C.muted },
  section: { marginTop: 22 },
  panel: {
    backgroundColor: C.panel,
    borderRadius: 6,
    padding: 14,
    borderLeft: `2 solid ${C.brassLight}`,
  },
  row: { flexDirection: "row" },
  between: { flexDirection: "row", justifyContent: "space-between" },
  th: {
    fontSize: 7,
    letterSpacing: 0.9,
    color: C.muted,
    fontFamily: "Helvetica-Bold",
    paddingBottom: 5,
  },
  td: { fontSize: 9, paddingVertical: 4.5 },
  trBorder: { borderBottom: `0.5 solid ${C.rule}` },
  footer: {
    position: "absolute",
    bottom: 26,
    left: 44,
    right: 44,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7.5,
    color: C.muted,
    borderTop: `0.5 solid ${C.rule}`,
    paddingTop: 7,
  },
});

const money = (paisa: number) => Math.round(paisa / 100).toLocaleString("en-US");
const signed = (paisa: number) => `${paisa < 0 ? "-" : "+"}${money(Math.abs(paisa))}`;
const pct = (n: number) => `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
const shortDate = (d: string) => d.slice(0, 10);

/* ── Building blocks ──────────────────────────────────────────────────────── */

function Footer() {
  return (
    <View style={s.footer} fixed>
      <Text>Generated by PakFinance — figures derived from records you entered</Text>
      <Text render={({ pageNumber, totalPages }) => `${pageNumber} of ${totalPages}`} />
    </View>
  );
}

/**
 * Section heading.
 *
 * No `bookmark` here: @react-pdf types it on Page only, so the outline is built
 * page by page below. That is the right granularity anyway — a reader's sidebar
 * with four destinations is navigable, one with twenty is a second table of
 * contents nobody asked for.
 */
function SectionTitle({ children }: { children: string }) {
  return (
    <View style={s.section}>
      <Text style={s.h2}>{children}</Text>
    </View>
  );
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: string }) {
  return (
    <View style={{ flex: 1 }}>
      <Text style={{ fontSize: 7, letterSpacing: 0.9, color: C.muted, fontFamily: "Helvetica-Bold" }}>
        {label.toUpperCase()}
      </Text>
      <Text style={{ fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 4, color: tone ?? C.ink }}>
        {value}
      </Text>
    </View>
  );
}

/** Horizontal stacked bar. Proportions a table cannot show at a glance. */
function AllocationBar({ parts }: { parts: { label: string; value: number; color: string }[] }) {
  const total = parts.reduce((t, p) => t + p.value, 0);
  if (total <= 0) return null;

  const W = 500;

  // Each segment's offset is the sum of the ones before it, computed without
  // mutating a running total — render must not depend on a variable it is
  // changing as it goes. Quadratic, over at most six segments.
  const segments = parts.map((p, i) => ({
    ...p,
    x: (parts.slice(0, i).reduce((t, q) => t + q.value, 0) / total) * W,
    width: (p.value / total) * W,
  }));

  return (
    <View>
      <Svg width={W} height={14} viewBox={`0 0 ${W} 14`}>
        {segments.map((seg) => (
          <Rect
            key={seg.label}
            x={seg.x}
            y={0}
            width={Math.max(0, seg.width - 1)}
            height={14}
            rx={2}
            fill={seg.color}
          />
        ))}
      </Svg>
      <View style={{ flexDirection: "row", marginTop: 8, flexWrap: "wrap" }}>
        {parts.map((p) => (
          <View key={p.label} style={{ flexDirection: "row", alignItems: "center", marginRight: 18 }}>
            <Svg width={7} height={7} viewBox="0 0 7 7">
              <Rect x={0} y={0} width={7} height={7} rx={1.5} fill={p.color} />
            </Svg>
            <Text style={{ marginLeft: 5, fontSize: 8.5 }}>
              {p.label} {((p.value / total) * 100).toFixed(0)}%
            </Text>
            <Text style={{ marginLeft: 4, fontSize: 8.5, color: C.muted }}>{money(p.value)}</Text>
          </View>
        ))}
      </View>
    </View>
  );
}

/** Net-worth line. Only drawn when the snapshot job has produced real points. */
function Trend({ series }: { series: { date: string; valuePaisa: number }[] }) {
  if (series.length < 2) return null;

  const W = 500;
  const H = 90;
  const values = series.map((p) => p.valuePaisa);
  const min = Math.min(...values);
  const max = Math.max(...values);
  const span = max - min || 1;

  const points = series
    .map((p, i) => {
      const x = (i / (series.length - 1)) * W;
      const y = H - ((p.valuePaisa - min) / span) * (H - 8) - 4;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    })
    .join(" ");

  return (
    <View>
      <Svg width={W} height={H} viewBox={`0 0 ${W} ${H}`}>
        <Rect x={0} y={0} width={W} height={H} fill={C.panel} rx={4} />
        <Polyline points={points} fill="none" stroke={C.brass} strokeWidth={1.6} />
      </Svg>
      <View style={[s.between, { marginTop: 5 }]}>
        <Text style={{ fontSize: 7.5, color: C.muted }}>
          {shortDate(series[0].date)} · {money(series[0].valuePaisa)}
        </Text>
        <Text style={{ fontSize: 7.5, color: C.muted }}>
          {shortDate(series[series.length - 1].date)} · {money(series[series.length - 1].valuePaisa)}
        </Text>
      </View>
    </View>
  );
}

/** Thin progress bar for loans and goals. */
function Progress({ value, color }: { value: number; color: string }) {
  const W = 90;
  const filled = Math.max(0, Math.min(100, value)) / 100;
  return (
    <Svg width={W} height={5} viewBox={`0 0 ${W} 5`}>
      <Rect x={0} y={0} width={W} height={5} rx={2.5} fill={C.rule} />
      <Rect x={0} y={0} width={W * filled} height={5} rx={2.5} fill={color} />
    </Svg>
  );
}

function Table({
  columns,
  rows,
}: {
  columns: { key: string; label: string; width: number; align?: "left" | "right" }[];
  rows: (string | { text: string; color?: string; bar?: number })[][];
}) {
  return (
    <View>
      <View style={[s.row, s.trBorder]}>
        {columns.map((c) => (
          <Text
            key={c.key}
            style={[s.th, { width: `${c.width}%`, textAlign: c.align ?? "left" }]}
          >
            {c.label.toUpperCase()}
          </Text>
        ))}
      </View>

      {rows.map((r, i) => (
        <View key={i} style={[s.row, s.trBorder]} wrap={false}>
          {r.map((cell, j) => {
            const col = columns[j];
            const isObj = typeof cell !== "string";
            const text = isObj ? cell.text : cell;
            return (
              <View key={j} style={{ width: `${col.width}%` }}>
                <Text
                  style={[
                    s.td,
                    {
                      textAlign: col.align ?? "left",
                      color: isObj && cell.color ? cell.color : C.body,
                    },
                  ]}
                >
                  {text}
                </Text>
                {isObj && cell.bar !== undefined && (
                  <View style={{ marginBottom: 5 }}>
                    <Progress value={cell.bar} color={C.brassLight} />
                  </View>
                )}
              </View>
            );
          })}
        </View>
      ))}
    </View>
  );
}

function InsightCard({ item }: { item: Insight }) {
  const tone = item.tone === "good" ? C.gain : item.tone === "watch" ? C.watch : C.muted;
  return (
    <View style={[s.panel, { marginBottom: 9, borderLeft: `2 solid ${tone}` }]} wrap={false}>
      <Text style={[s.h3, { color: tone }]}>{item.title}</Text>
      <Text style={{ marginTop: 3, color: C.body }}>{item.body}</Text>
    </View>
  );
}

/* ── The document ─────────────────────────────────────────────────────────── */

function Report({ data }: { data: ReportData }) {
  const {
    name,
    generatedAt,
    priceAsOf,
    breakdown,
    holdings,
    positions,
    fundMeta,
    accounts,
    loans,
    goals,
    flow,
    txns,
    series,
    bySector,
    insights,
  } = data;

  const stamp = generatedAt.toLocaleDateString("en-GB", {
    timeZone: "Asia/Karachi",
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <Document
      title={`PakFinance report — ${name}`}
      author="PakFinance"
      subject="Personal portfolio report"
    >
      <Page size="A4" style={s.page} bookmark={{ title: "Summary & insights", fit: true }}>
        <Footer />

        <View>
          <Text style={s.eyebrow}>PAKFINANCE · PORTFOLIO REPORT</Text>
          <Text style={s.h1}>{name}</Text>
          <Text style={[s.muted, { marginTop: 3 }]}>
            Prepared {stamp}
            {priceAsOf
              ? ` · PSX prices as of ${priceAsOf.toLocaleString("en-GB", {
                  timeZone: "Asia/Karachi",
                  day: "numeric",
                  month: "short",
                  hour: "2-digit",
                  minute: "2-digit",
                })} PKT`
              : ""}
          </Text>
        </View>

        <View style={[s.row, { marginTop: 22, gap: 10 }]}>
          <Stat label="Net worth" value={money(breakdown.netPaisa)} />
          <Stat label="Assets" value={money(breakdown.assetsPaisa)} />
          <Stat
            label="Liabilities"
            value={money(breakdown.liabilitiesPaisa)}
            tone={breakdown.liabilitiesPaisa > 0 ? C.loss : undefined}
          />
        </View>
        <Text style={[s.muted, { fontSize: 7.5, marginTop: 6 }]}>
          All figures in Pakistani rupees.
        </Text>

        <SectionTitle>Where your money is</SectionTitle>
        <AllocationBar
          parts={[
            { label: "Stocks", value: breakdown.psxPaisa, color: C.brass },
            { label: "Funds", value: breakdown.fundsPaisa, color: "#5B7C99" },
            { label: "Cash", value: breakdown.cashPaisa, color: "#6E8B6E" },
          ]}
        />

        {series.length > 1 && (
          <>
            <SectionTitle>Net worth over time</SectionTitle>
            <Trend series={series} />
            <Text style={[s.muted, { fontSize: 7.5, marginTop: 5 }]}>
              Recorded daily from the day tracking began. Bank balances and fund NAVs
              cannot be reconstructed for dates before that, so the line starts where
              the record does rather than guessing backwards.
            </Text>
          </>
        )}

        <SectionTitle>What stands out</SectionTitle>
        {insights.map((item, i) => (
          <InsightCard key={i} item={item} />
        ))}
      </Page>

      {/* Investments */}
      {(holdings.length > 0 || positions.length > 0) && (
        <Page size="A4" style={s.page} bookmark={{ title: "Investments", fit: true }}>
          <Footer />

          {holdings.length > 0 && (
            <>
              <View>
                <Text style={s.h2}>Stock holdings</Text>
              </View>
              <Table
                columns={[
                  { key: "sym", label: "Scrip", width: 16 },
                  { key: "qty", label: "Qty", width: 12, align: "right" },
                  { key: "avg", label: "Avg cost", width: 15, align: "right" },
                  { key: "last", label: "Last", width: 14, align: "right" },
                  { key: "val", label: "Value", width: 18, align: "right" },
                  { key: "ret", label: "Return", width: 12, align: "right" },
                  { key: "wt", label: "Weight", width: 13, align: "right" },
                ]}
                rows={holdings.map((h) => [
                  { text: h.symbol, color: C.ink },
                  h.qty.toLocaleString("en-US"),
                  money(Math.round(h.avgCostPaisa)),
                  h.lastPaisa === null ? "—" : money(h.lastPaisa),
                  { text: money(h.valuePaisa), color: C.ink },
                  {
                    text: pct(h.returnPct),
                    color: h.unrealisedPaisa >= 0 ? C.gain : C.loss,
                  },
                  breakdown.psxPaisa
                    ? `${((h.valuePaisa / breakdown.psxPaisa) * 100).toFixed(0)}%`
                    : "—",
                ])}
              />

              {bySector.length > 0 && (
                <View style={{ marginTop: 14 }}>
                  <Text style={[s.h3, { marginBottom: 6 }]}>Sector concentration</Text>
                  <AllocationBar
                    parts={bySector.slice(0, 6).map((x, i) => ({
                      label: x.key,
                      value: x.valuePaisa,
                      color: ["#9A7B1C", "#5B7C99", "#6E8B6E", "#8B6E8B", "#99785B", "#5B8B8B"][i % 6],
                    }))}
                  />
                </View>
              )}
            </>
          )}

          {positions.length > 0 && (
            <>
              <SectionTitle>Mutual funds</SectionTitle>
              <Table
                columns={[
                  { key: "fund", label: "Fund", width: 40 },
                  { key: "units", label: "Units", width: 14, align: "right" },
                  { key: "nav", label: "NAV", width: 12, align: "right" },
                  { key: "val", label: "Value", width: 18, align: "right" },
                  { key: "ret", label: "Return", width: 16, align: "right" },
                ]}
                rows={positions.map((p) => [
                  { text: fundMeta.get(p.fundId)?.name ?? "Unknown fund", color: C.ink },
                  p.units.toLocaleString("en-US", { maximumFractionDigits: 2 }),
                  p.navPaisa === null ? "—" : (p.navPaisa / 100).toFixed(2),
                  { text: money(p.valuePaisa), color: C.ink },
                  { text: pct(p.returnPct), color: p.gainPaisa >= 0 ? C.gain : C.loss },
                ])}
              />
            </>
          )}
        </Page>
      )}

      {/* Money */}
      <Page size="A4" style={s.page} bookmark={{ title: "Cash, loans & goals", fit: true }}>
        <Footer />

        <View>
          <Text style={s.h2}>Cash and accounts</Text>
        </View>
        {accounts.length ? (
          <Table
            columns={[
              { key: "name", label: "Account", width: 44 },
              { key: "kind", label: "Type", width: 20 },
              { key: "as", label: "Confirmed", width: 18 },
              { key: "bal", label: "Balance", width: 18, align: "right" },
            ]}
            rows={accounts.map((a) => [
              { text: a.name, color: C.ink },
              a.kind.toLowerCase() + (a.masked_number ? ` ····${a.masked_number}` : ""),
              shortDate(String(a.as_of)),
              { text: money(a.balance_paisa), color: C.ink },
            ])}
          />
        ) : (
          <Text style={s.muted}>No accounts recorded.</Text>
        )}

        <SectionTitle>This month</SectionTitle>
        <View style={[s.row, { gap: 10 }]}>
          <Stat label="Money in" value={money(flow.incomePaisa)} tone={C.gain} />
          <Stat label="Money out" value={money(flow.expensesPaisa)} />
          <Stat
            label="Net"
            value={signed(flow.netPaisa)}
            tone={flow.netPaisa >= 0 ? C.gain : C.loss}
          />
        </View>

        {flow.categories.length > 0 && (
          <View style={{ marginTop: 14 }}>
            <Text style={[s.h3, { marginBottom: 6 }]}>Where it went</Text>
            <Table
              columns={[
                { key: "cat", label: "Category", width: 56 },
                { key: "amt", label: "Amount", width: 22, align: "right" },
                { key: "pct", label: "Share", width: 22, align: "right" },
              ]}
              rows={flow.categories.slice(0, 10).map((c) => [
                { text: c.key, color: C.ink },
                money(c.value),
                `${c.pct.toFixed(0)}%`,
              ])}
            />
          </View>
        )}

        {loans.length > 0 && (
          <>
            <SectionTitle>Loans</SectionTitle>
            <Table
              columns={[
                { key: "name", label: "Loan", width: 30 },
                { key: "lender", label: "Lender", width: 20 },
                { key: "orig", label: "Original", width: 16, align: "right" },
                { key: "rem", label: "Outstanding", width: 18, align: "right" },
                { key: "prog", label: "Repaid", width: 16, align: "right" },
              ]}
              rows={loans.map((l) => [
                { text: l.name, color: C.ink },
                l.lender ?? "—",
                money(l.principal_paisa),
                { text: money(l.remainingPaisa), color: C.ink },
                { text: `${l.repaidPct.toFixed(0)}%`, bar: l.repaidPct },
              ])}
            />
          </>
        )}

        {goals.length > 0 && (
          <>
            <SectionTitle>Goals</SectionTitle>
            <Table
              columns={[
                { key: "name", label: "Goal", width: 28 },
                { key: "target", label: "Target", width: 16, align: "right" },
                { key: "saved", label: "Saved", width: 16, align: "right" },
                { key: "by", label: "By", width: 14 },
                { key: "need", label: "Monthly", width: 14, align: "right" },
                { key: "prog", label: "Progress", width: 12, align: "right" },
              ]}
              rows={goals.map((g) => [
                { text: g.name, color: C.ink },
                money(g.target_paisa),
                money(g.savedPaisa),
                g.target_date ?? "—",
                {
                  text: g.target_date ? money(g.monthlyNeededPaisa) : "—",
                  color: g.onTrack ? C.body : C.watch,
                },
                { text: `${g.pct.toFixed(0)}%`, bar: g.pct },
              ])}
            />
          </>
        )}
      </Page>

      {/* Ledger */}
      {txns.length > 0 && (
        <Page size="A4" style={s.page} bookmark={{ title: "Recent transactions", fit: true }}>
          <Footer />
          <View>
            <Text style={s.h2}>Recent transactions</Text>
          </View>
          <Table
            columns={[
              { key: "date", label: "Date", width: 16 },
              { key: "label", label: "Description", width: 44 },
              { key: "cat", label: "Category", width: 20 },
              { key: "amt", label: "Amount", width: 20, align: "right" },
            ]}
            rows={txns.slice(0, 40).map((t) => [
              shortDate(String(t.occurred_at)),
              { text: t.label, color: C.ink },
              t.category ?? "—",
              {
                text: signed(t.amount_paisa),
                color: t.amount_paisa > 0 ? C.gain : C.body,
              },
            ])}
          />
          <Text style={[s.muted, { fontSize: 7.5, marginTop: 10 }]}>
            The 40 most recent movements. For the complete ledger, export as CSV or
            JSON from Settings — those contain everything without truncation.
          </Text>

          <View style={[s.panel, { marginTop: 20 }]}>
            <Text style={s.h3}>About this report</Text>
            <Text style={{ marginTop: 3, color: C.body }}>
              Every figure is derived from records you entered. Stock values use the
              most recent PSX close held by PakFinance; fund values use the latest
              published NAV. Nothing here is investment advice, and PakFinance is not
              a licensed adviser.
            </Text>
            <Link src="https://pakfinance.app" style={{ marginTop: 6, color: C.brass, fontSize: 8.5 }}>
              Open PakFinance
            </Link>
          </View>
        </Page>
      )}
    </Document>
  );
}

/** Render to a Buffer. Kept here so route handlers need no JSX. */
export function renderReport(data: ReportData): Promise<Buffer> {
  return renderToBuffer(<Report data={data} />);
}
